POST http://18.205.17.8:8080/api/auth/signup
Content-Type: application/json
Authorization: Bearer 1234566788

{
    "username": "Abdel",
    "email": "Abdel@gmail.com",
    "role": [
        "admin"
    ],
    "password": "!112233"
}